### ISSUE TITLE
Maven install not works

### ISSUE THREAD

**Issue by szabobar** [EmiteGWT/emite#22]
Hi,

I was downloaded the project, and tried to intall with mvn like this:
mvn install:install-file -DgroupId=org.tigase -DartifactId=tigase-xmltools -Dversion=2.3.0 -Dpackaging=jar -Dfile=lib/tigase-xmltools-2.3.0.jar

The result:
[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'install'.
[INFO] ------------------------------------------------------------------------
[INFO] Building Emite XMPP Library
[INFO]    task-segment: [install:install-file](aggregator-style)
[INFO] ------------------------------------------------------------------------
[INFO] [install:install-file {execution: default-cli}]
[INFO] Installing /home/barnabas/Dropbox/Work/workspace/emite_gwt_jabber/lib/tigase-xmltools-2.3.0.jar to /home/barnabas/.m2/repository/org/tigase/tigase-xmltools/2.3.0/tigase-xmltools-2.3.0.jar
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error installing artifact 'org.tigase:tigase-xmltools:jar': Error installing artifact: File /home/barnabas/Dropbox/Work/workspace/emite_gwt_jabber/lib/tigase-xmltools-2.3.0.jar does not exist

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Sun May 08 10:18:12 CEST 2011
[INFO] Final Memory: 8M/56M
[INFO] ------------------------------------------------------------------------

**Comment by xose** [comment]
This is no longer required. Just run `mvn install -DskipTests=true` to install Emite.
